name: testing

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        runs: |
          apt-get update -y && apt-get install -y bsdmainutils
      - name: Test with bash script
        run: |
          bash example.sh -a 99 --gender male

  test-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test with bash script
        run: |
          bash example.sh -a 99 --gender male

  test-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test with bash script
        run: |
          bash example.sh -a 99 --gender male
